#!/bin/bash
#
#
# $Id: snort-sensor,v 1.4 2007/06/07 14:47:08 hanashi Exp $
#
# Copyright (C) 2005, David J. Bianco <david@vorant.com>
#
# This program is distributed under the terms of version 1.0 of the
# Q Public License.  See LICENSE.QPL for further details.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# snort	   start and stop snort IDS sensor
#
# chkconfig: 345 81 14
# description: start and stop IDS sensor

PATH=/sbin:/bin:/usr/bin:/usr/sbin

# Source function library.
#. /etc/init.d/functions

# The name of this sensor.  Edit this!
SENSOR=agente1

# The location of the local storage directory.  Edit this!
NSMDIR=/nsm

# The network interface to monitor (eg, eth2, bond0, etc).  Edit this!
IFACE=eth0

RETVAL=0

# The location of the Snort log directory. 
SNORTLOG=/$NSMDIR/$SENSOR/snortlog

SNORT="/usr/bin/snort -u sguil -g sguil -m 122 -l $SNORTLOG -c /nsm/etc/snort.conf -D -i $IFACE -q -A none -U "

start(){
   echo -n "Starting snort: "

    # Since we're running as nobody, make sure the logs are writable by us
    chown -R  sguil.sguil $SNORTLOG
    $SNORT
    RETVAL=$?
    echo
    return $RETVAL
}

stop(){
    echo -n "Stopping snort: "
    kill -9	`ps auxww | grep snort | grep snort.conf | grep $SENSOR | awk '{print $2}'`
    RETVAL=$?
    echo
    return $RETVAL

}

restart(){
    stop
    start
}

status() {
    PID=`ps auxww | grep snort | grep snort.conf | grep $SENSOR | grep -v grep | awk '{print $2}'`
    if [ "x$PID" != "x" ]; then
	echo "Snort NIDS for sensor $SENSOR is UP (pid $PID)"
	exit 0
    else
	echo "Snort NIDS for sensor $SENSOR is DOWN"
	exit -1
    fi
}

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status $prog
	;;
    restart)
	restart
	;;
    *)
	echo $"Usage: $0 {start|stop|status|restart}"
	RETVAL=1
esac

exit $RETVAL
